#!/bin/sh
#
# PROVIDE: mylar
# REQUIRE: NETWORKING SERVERS DAEMON ldconfig resolv
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# mylar_enable (bool):  Set to NO by default.
#                       Set it to YES to enable it.
# mylar_data_dir:       Directory where mylar configuration
#                       data is stored.
#                       Default: /usr/local/share/mylar
# mylar_user:           The user account mylar daemon runs as what
#                       you want it to be.
#                       Default: media
# mylar_group:          The group account mylar daemon runs as what
#                       you want it to be.
#                       Default: media

. /etc/rc.subr
name="mylar"
rcvar="${name}_enable"
load_rc_config $name

: ${mylar_enable:="NO"}
: ${mylar_user:="media"}
: ${mylar_group:="media"}
: ${mylar_dir:="/usr/local/share/mylar"}
: ${mylar_data_dir:="/usr/local/mylar"}

pidfile="/var/run/mylar/mylar.pid"
command="/usr/local/bin/python2.7"
command_args="$mylar_dir/Mylar.py --config $mylar_data_dir/config.ini --datadir $mylar_data_dir -d --pidfile $pidfile -q --nolaunch"

start_precmd="mylar_prestart"
mylar_prestart() {
	export LC_ALL=en_US.UTF-8
	export LANG=en_US.UTF-8

	if [ -f $pidfile ]; then
		if [ ! `pgrep -F $pidfile` ]; then
			rm $pidfile
			echo "Removing stale pidfile."
		fi
	fi
}

run_rc_command "$1"
