#!/bin/sh

# PROVIDE: nzbhydra
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# nzbhydra_enable (bool):   Set to NO by default.
#                           Set it to YES to enable it.
# nzbhydra_user:            The user account nzbhydra daemon runs as what
#                           you want it to be.
#                           Default: media
# nzbhydra_group:           The group account nzbhydra daemon runs as what
#                           you want it to be.
#                           Default: media
# nzbhydra_dir:             Directory where nzbhydra installation
#                           data is stored.
#                           Default: /usr/local/share/nzbhydra
# nzbhydra_data_dir:        Directory where nzbhydra configuration
#                           data is stored.
#                           Default: /var/db/nzbhydra


. /etc/rc.subr

name="nzbhydra"
rcvar="${name}_enable"
load_rc_config ${name}

: ${nzbhydra_enable:="NO"}
: ${nzbhydra_user:="media"}
: ${nzbhydra_group:="media"}
: ${nzbhydra_dir:="/usr/local/share/nzbhydra"}
: ${nzbhydra_data_dir:="/var/db/nzbhydra"}

pidfile="/var/run/nzbhydra/nzbhydra.pid"
command="/usr/local/bin/python2.7"
command_args="$nzbhydra_dir/nzbhydra.py --config $nzbhydra_data_dir/settings.cfg --datadir $nzbhydra_data_dir/nzbhydra.db --pidfile ${pidfile} --nobrowser --daemon"

start_precmd="nzbhydra_prestart"
nzbhydra_prestart() {
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8

        if [ -f ${pidfile} ]; then
                rm -f ${pidfile}
                echo "Removing stale pidfile."
        elif [ ! -d ${pidfile%/*} ]; then
                install -d -o ${nzbhydra_user} -g ${nzbhydra_group} ${pidfile%/*}
        fi

        if [ ! -d ${nzbhydra_data_dir} ]; then
                install -d -o ${nzbhydra_user} -g ${nzbhydra_group} ${nzbhydra_data_dir}
        fi
}

run_rc_command "$1"