#!/bin/sh
#
# PROVIDE: plexpy
# REQUIRE: DAEMON plexpy
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# plexpy_enable (bool): Set to NO by default.
#                       Set it to YES to enable it.
# plexpy_user:          The user account PlexPy daemon runs as what
#                       you want it to be.
#                       Default: plexpy
# plexpy_group:         The group account PlexPy daemon runs as what
#                       you want it to be.
#                       Default: plexpy
# plexpy_dir:           Directory where PlexPy lives.
#                       Default: /usr/local/share/plexpy
# plexpy_data_dir:      Directory where PlexPy configuration
#                       data is stored.
#                       Default: /var/db/plexpy

. /etc/rc.subr

name="plexpy"
rcvar=${name}_enable

load_rc_config ${name}

: ${plexpy_enable:="NO"}
: ${plexpy_user:="plexpy"}
: ${plexpy_group:="plexpy"}
: ${plexpy_dir:="/usr/local/share/plexpy"}
: ${plexpy_data_dir:="/var/db/plexpy"}
: ${plexpy_flags:=""}

pidfile="/var/run/plexpy/plexpy.pid"
command="/usr/local/bin/python2.7"
command_args="${plexpy_dir}/PlexPy.py --daemon --datadir ${plexpy_data_dir} --pidfile ${pidfile} --quiet --nolaunch ${plexpy_flags}"

start_precmd="${name}_prestart"
plexpy_prestart() {
    if [ -f $pidfile ]; then
        if [ ! `pgrep -F $pidfile` ]; then
            rm $pidfile
            echo "Removing stale pidfile."
        fi
    fi
}

run_rc_command "$1"