#!/bin/sh
#
# PROVIDE: sickgear
# REQUIRE: NETWORKING SERVERS DAEMON ldconfig resolv
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# sickgear_enable (bool):   Set to NO by default.
#                           Set it to YES to enable it.
#
# sickgear_data_dir:        Directory where sickgear configuration
#                           data is stored.
#                           Default: /usr/local/sickgear
#
# sickgear_user:            The user account sickgear daemon runs as what
#                           you want it to be.
#                           Default: media
#
# sickgear_group:           The group account sickgear daemon runs as what
#                           you want it to be.
#                           Default: media

. /etc/rc.subr
name="sickgear"
rcvar="${name}_enable"
load_rc_config $name

: ${sickgear_enable:="NO"}
: ${sickgear_user:="media"}
: ${sickgear_group:="media"}
: ${sickgear_dir:="/usr/local/share/sickgear"}
: ${sickgear_data_dir:="/usr/local/sickgear"}

pidfile="/var/run/sickgear/sickgear.pid"
command="/usr/local/bin/python2.7"
command_args="$sickgear_dir/SickBeard.py --config $sickgear_data_dir/config.ini --datadir $sickgear_data_dir -d --pidfile $pidfile -q --nolaunch"

start_precmd="${name}_prestart"
sickgear_prestart() {
	export LC_ALL=en_US.UTF-8
	export LANG=en_US.UTF-8

	if [ -f $pidfile ]; then
		if [ ! `pgrep -F $pidfile` ]; then
			rm $pidfile
			echo "Removing stale pidfile."
		fi
	fi
}

run_rc_command "$1"
